# Generated by Django 3.2.8 on 2021-10-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todolist_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[(1, 'هیچ'), (2, 'سبز'), (3, 'زرد'), (4, 'نارنجی'), (5, 'قرمز')], default=1, max_length=10, verbose_name='اولویت'),
        ),
    ]
